package model;

/**
 * Códigos de erro da validação do cliente
 */
public enum ErroCliente {
	CPF_INVALIDO,
	CPF_JA_EXISTE,
	NOME_INVALIDO,
	DATA_INVALIDA,
	IDADE_INVALIDA,
	ENDERECO_INVALIDO,
	TELEFONE_INVALIDO,
	LOGRADOURO_INVALIDO,
	NUMERO_INVALIDO,
	BAIRRO_INVALIDO,
	CIDADE_INVALIDA,
	CEP_INVALIDO,
	UF_INVALIDA,
	DDD_INVALIDO,
	NUMERO_TEL_INVALIDO
}
